### ISSUE TITLE
Tabs shouldn't jump to anchor (Chrome)

### ISSUE THREAD

**Issue by luukdv** [trendwerk/tabs#2]
Personally, I think this isn't user friendly. Especially when there are a few different tabs, everytime you select one the page jumps to this anchor. This causes the content to move towards the very top of the page and the tab selectors itself to disappear from the direct view. You have to scroll up every time you want to select another tab.

From a user point of view I think this is blocking the natural scanning of a page because the content makes a (big) jump and your eyes have to readjust position.

How does everyone feel about this?

**Comment by sboerrigter** [comment]
I agree

**Comment by haroldangenent** [comment]
Agreed, but this is specifically a bug in Chrome. It's specifically coded _not_ to do that, so marking this as a bug.

**Comment by luukdv** [comment]
I can't reproduce this, tested on different versions of Chrome and different installs. Seems to be a project-specific bug. Has anyone besides me encountered this problem somewhere?

**Comment by haroldangenent** [comment]
Nope. Closing this.
